spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/raishin?autoReconnect=true&useSSL=false
    username: raishin
    password: yukiyuki
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: raishin7773@gmail.com
    password: takadash0007
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true