spring:
  profiles:
    active: pos
    
---
spring:
  profiles: pos
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${databaseurl}
    username: raishin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailaddress}
    password: ${mailpass}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
---
    
server:
    port: 5000
    