spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${hostname}/${dbname}?sslmode=require
    username: ${username}
    password: ${password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailaddress}
    password: ${mailpass}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5000
